version: '3'
services:
  app:
    image: company/project
    ports:
      - 8080:8080
    networks:
      - project-net
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - project-net
    volumes:
      - redis-data:/data

networks:
  project-net:

volumes:
  redis-data:
